// <auto-generated />
using System;
using ArtGallery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtGallery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422152637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtGallery.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Испанский художник-сюрреалист, один из самых известных представителей этого направления. Его работы отличаются фантастическими образами и виртуозной живописной техникой.",
                            Country = "Испания",
                            Name = "Сальвадор Дали",
                            PhotoUrl = "/images/authors/dali_author.jpg",
                            Style = "Сюрреализм",
                            Years = "1904–1989"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Русский художник-пейзажист, академик. Один из крупнейших мастеров реалистической пейзажной живописи. Его картины отличаются тщательной прорисовкой деталей природы.",
                            Country = "Россия",
                            Name = "Иван Шишкин",
                            PhotoUrl = "/images/authors/shishkin_author.jpg",
                            Style = "Реализм",
                            Years = "1832–1898"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Нидерландский художник-постимпрессионист. За свою короткую жизнь создал более 2000 произведений. Его экспрессивная манера оказала огромное влияние на всё западное искусство.",
                            Country = "Нидерланды",
                            Name = "Винсент Ван Гог",
                            PhotoUrl = "/images/authors/vangogh_author.jpg",
                            Style = "Постимпрессионизм",
                            Years = "1853–1890"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Русский живописец и график, мастер портрета. Один из крупнейших русских художников рубежа XIX–XX веков. Прославился портретами представителей российской интеллигенции.",
                            Country = "Россия",
                            Name = "Валентин Серов",
                            PhotoUrl = "/images/authors/serov_author.jpg",
                            Style = "Реализм",
                            Years = "1865–1911"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Испанский художник, скульптор, график. Основатель кубизма. Один из самых известных и влиятельных художников XX века. Создал более 20 000 произведений.",
                            Country = "Испания",
                            Name = "Пабло Пикассо",
                            PhotoUrl = "/images/authors/picasso_author.jpg",
                            Style = "Кубизм",
                            Years = "1881–1973"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Французский живописец, основоположник импрессионизма. Работал преимущественно на пленэре. Создал знаменитые серии «Стога сена», «Руанский собор», «Кувшинки».",
                            Country = "Франция",
                            Name = "Клод Моне",
                            PhotoUrl = "/images/authors/monet_author.jpg",
                            Style = "Импрессионизм",
                            Years = "1840–1926"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Русский и советский художник, педагог, теоретик искусства. Основатель супрематизма — одного из наиболее ранних проявлений абстрактного искусства.",
                            Country = "Россия",
                            Name = "Казимир Малевич",
                            PhotoUrl = "/images/authors/malevich_author.jpg",
                            Style = "Супрематизм",
                            Years = "1879–1935"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Норвежский живописец и график, театральный художник. Один из первых представителей экспрессионизма. Его работы оказали значительное влияние на развитие этого направления.",
                            Country = "Норвегия",
                            Name = "Эдвард Мунк",
                            PhotoUrl = "/images/authors/munch_author.jpg",
                            Style = "Экспрессионизм",
                            Years = "1863–1944"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Итальянский художник, учёный, изобретатель, писатель, музыкант эпохи Высокого Возрождения. Гений, совместивший в себе художника и учёного.",
                            Country = "Италия",
                            Name = "Леонардо да Винчи",
                            PhotoUrl = "/images/authors/davinci_author.jpg",
                            Style = "Возрождение",
                            Years = "1452–1519"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Русский живописец, педагог. Один из крупнейших мастеров русского реализма. Создал обширную галерею портретов современников, а также жанровые и исторические картины.",
                            Country = "Россия",
                            Name = "Илья Репин",
                            PhotoUrl = "/images/authors/repin_author.jpg",
                            Style = "Реализм",
                            Years = "1844–1930"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Американский художник, известный своим стилем «искусственный реализм». Сочетает классические живописные техники с гротескными, юмористическими образами.",
                            Country = "США",
                            Name = "Джордж Кондо",
                            PhotoUrl = "/images/authors/condo_avatar.jpg",
                            Style = "Поп-арт",
                            Years = "1957–н.в."
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Японский художник и предприниматель. Создатель стиля «суперфлат». Работы сочетают традиционные японские мотивы с западной поп-культурой.",
                            Country = "Япония",
                            Name = "Такаси Мураками",
                            PhotoUrl = "/images/authors/murakami_avatar.jpg",
                            Style = "Поп-арт",
                            Years = "1962–н.в."
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Российский художник, представитель московского акционизма и постсоветского искусства. Работает с образами архитектурных памятников, используя нетрадиционные материалы.",
                            Country = "Россия",
                            Name = "Валерий Кошляков",
                            PhotoUrl = "/images/authors/koshlyakov_avatar.jpg",
                            Style = "Современное искусство",
                            Years = "1962–н.в."
                        });
                });

            modelBuilder.Entity("ArtGallery.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaintingId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaintingId", "SessionId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ArtGallery.Models.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Сальвадор Дали",
                            Country = "Испания",
                            Description = "\"Постоянство памяти\" — одна из самых известных работ Сальвадора Дали. На картине изображены мягкие, плавящиеся карманные часы на фоне пустынного пейзажа. Символ сюрреализма и размышление о гибкости времени.",
                            ImageUrl = "/images/paintings/collection1.jpg",
                            Materials = "Масло, холст",
                            Size = "24 × 33 см",
                            Style = "Сюрреализм",
                            Title = "Постоянство памяти",
                            Year = 1931
                        },
                        new
                        {
                            Id = 2,
                            Author = "Иван Шишкин",
                            Country = "Россия",
                            Description = "Картина «Утро в сосновом лесу» — одно из самых известных произведений Ивана Шишкина. Художник мастерски изобразил утренний лес, пронизанный солнечным светом. Медведи дописаны Константином Савицким.",
                            ImageUrl = "/images/paintings/collection2.jpg",
                            Materials = "Масло, холст",
                            Size = "139 × 213 см",
                            Style = "Реализм",
                            Title = "Утро в сосновом лесу",
                            Year = 1889
                        },
                        new
                        {
                            Id = 3,
                            Author = "Винсент Ван Гог",
                            Country = "Нидерланды",
                            Description = "\"Звёздная ночь\" — одна из самых узнаваемых картин Ван Гога. Художник изобразил ночной пейзаж с динамичными вихревыми облаками и яркими звёздами.",
                            ImageUrl = "/images/paintings/painting3.jpg",
                            Materials = "Масло, холст",
                            Size = "73.7 × 92.1 см",
                            Style = "Постимпрессионизм",
                            Title = "Звёздная ночь",
                            Year = 1889
                        },
                        new
                        {
                            Id = 4,
                            Author = "Валентин Серов",
                            Country = "Россия",
                            Description = "\"Девочка с персиками\" — знаменитая картина Серова, написанная в усадьбе Абрамцево. На полотне изображена Вера Мамонтова. Эталон русского реализма.",
                            ImageUrl = "/images/paintings/painting4.jpg",
                            Materials = "Масло, холст",
                            Size = "91 × 85 см",
                            Style = "Реализм",
                            Title = "Девочка с персиками",
                            Year = 1887
                        },
                        new
                        {
                            Id = 5,
                            Author = "Пабло Пикассо",
                            Country = "Испания",
                            Description = "\"Герника\" — монументальное полотно Пикассо, созданное в ответ на бомбардировку баскского города. Символ протеста против войны и насилия.",
                            ImageUrl = "/images/paintings/painting5.jpg",
                            Materials = "Масло, холст",
                            Size = "349 × 776 см",
                            Style = "Кубизм",
                            Title = "Герника",
                            Year = 1937
                        },
                        new
                        {
                            Id = 6,
                            Author = "Клод Моне",
                            Country = "Франция",
                            Description = "Картина Клода Моне, давшая название всему направлению импрессионизма. Художник изобразил гавань Гавра в утреннем тумане.",
                            ImageUrl = "/images/paintings/painting6.jpg",
                            Materials = "Масло, холст",
                            Size = "48 × 63 см",
                            Style = "Импрессионизм",
                            Title = "Впечатление. Восходящее солнце",
                            Year = 1872
                        },
                        new
                        {
                            Id = 7,
                            Author = "Казимир Малевич",
                            Country = "Россия",
                            Description = "\"Чёрный квадрат\" — самая известная работа Малевича, ставшая иконой супрематизма и всего русского авангарда.",
                            ImageUrl = "/images/paintings/painting7.jpg",
                            Materials = "Масло, холст",
                            Size = "79.5 × 79.5 см",
                            Style = "Супрематизм",
                            Title = "Чёрный квадрат",
                            Year = 1915
                        },
                        new
                        {
                            Id = 8,
                            Author = "Эдвард Мунк",
                            Country = "Норвегия",
                            Description = "\"Крик\" — знаменитая картина Эдварда Мунка, выражающая экзистенциальный ужас современного человека.",
                            ImageUrl = "/images/paintings/painting8.jpg",
                            Materials = "Масло, темпера, картон",
                            Size = "91 × 73.5 см",
                            Style = "Экспрессионизм",
                            Title = "Крик",
                            Year = 1893
                        },
                        new
                        {
                            Id = 9,
                            Author = "Леонардо да Винчи",
                            Country = "Италия",
                            Description = "\"Мона Лиза\" — всемирно известный портрет кисти Леонардо да Винчи, эталон портретной живописи эпохи Возрождения.",
                            ImageUrl = "/images/paintings/painting9.jpg",
                            Materials = "Масло, тополь",
                            Size = "77 × 53 см",
                            Style = "Возрождение",
                            Title = "Мона Лиза",
                            Year = 1503
                        },
                        new
                        {
                            Id = 10,
                            Author = "Винсент Ван Гог",
                            Country = "Нидерланды",
                            Description = "\"Подсолнухи\" — серия картин Ван Гога с подсолнухами в вазе. Яркие цвета и эмоциональная насыщенность делают их узнаваемыми во всём мире.",
                            ImageUrl = "/images/paintings/painting10.jpg",
                            Materials = "Масло, холст",
                            Size = "92 × 73 см",
                            Style = "Постимпрессионизм",
                            Title = "Подсолнухи",
                            Year = 1888
                        },
                        new
                        {
                            Id = 11,
                            Author = "Пабло Пикассо",
                            Country = "Испания",
                            Description = "\"Авиньонские девицы\" — новаторская работа Пикассо, предтеча кубизма. Радикальный разрыв с традиционной перспективой.",
                            ImageUrl = "/images/paintings/painting11.jpg",
                            Materials = "Масло, холст",
                            Size = "243.9 × 233.7 см",
                            Style = "Кубизм",
                            Title = "Авиньонские девицы",
                            Year = 1907
                        },
                        new
                        {
                            Id = 12,
                            Author = "Илья Репин",
                            Country = "Россия",
                            Description = "\"Бурлаки на Волге\" — знаменитая картина Репина, изображающая группу бурлаков. Символ социальной несправедливости.",
                            ImageUrl = "/images/paintings/painting12.jpg",
                            Materials = "Масло, холст",
                            Size = "131.5 × 281 см",
                            Style = "Реализм",
                            Title = "Бурлаки на Волге",
                            Year = 1873
                        },
                        new
                        {
                            Id = 13,
                            Author = "Джордж Кондо",
                            Country = "США",
                            Description = "\"Буги-Вуги\" — работа американского художника Джорджа Кондо в стиле «искусственный реализм». Сочетает гротескные формы с элементами поп-арта.",
                            ImageUrl = "/images/paintings/condo_boogie.jpg",
                            Materials = "Акрил, холст",
                            Size = "203 × 183 см",
                            Style = "Поп-арт",
                            Title = "Буги-Вуги",
                            Year = 2018
                        },
                        new
                        {
                            Id = 14,
                            Author = "Такаси Мураками",
                            Country = "Япония",
                            Description = "\"Цветы 727-727\" — работа Такаси Мураками. Яркие улыбающиеся цветы сочетают японскую эстетику с современной поп-культурой.",
                            ImageUrl = "/images/paintings/murakami_flowers.jpg",
                            Materials = "Акрил, холст",
                            Size = "100 × 100 см",
                            Style = "Поп-арт",
                            Title = "Цветы 727-727",
                            Year = 2022
                        },
                        new
                        {
                            Id = 15,
                            Author = "Валерий Кошляков",
                            Country = "Россия",
                            Description = "«Венеция. Палаццо» — работа Кошлякова. Художник использует нетрадиционные материалы для монументальных изображений архитектурных памятников.",
                            ImageUrl = "/images/paintings/koshlyakov_venice.jpg",
                            Materials = "Картон, темпера",
                            Size = "120 × 80 см",
                            Style = "Современное искусство",
                            Title = "Венеция. Палаццо",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("ArtGallery.Models.Favorite", b =>
                {
                    b.HasOne("ArtGallery.Models.Painting", "Painting")
                        .WithMany()
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painting");
                });
#pragma warning restore 612, 618
        }
    }
}
